SELECT 
'Raportul are date '
  AS REZULTAT
FROM VW_DATA_ALL D
WHERE
    D.PERIOADA = :PERIOADA
    AND D.CUIIO = :CUIIO
    AND (D.CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS = -1)
    AND D.FORM = :FORM
    AND D.FORM_VERS = :FORM_VERS 
    
    AND (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
   (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
   (:ID_MD=:ID_MD               OR  :ID_MD <> :ID_MD) AND
    D.FORM = 73
    
    
     
    
    
    HAVING 
    
    SUM(CASE WHEN D.CAPITOL = 100 AND RIND NOT IN ('1') THEN NVAL(D.COL1) ELSE 0 END) >  0
    
    AND 
    
    SUM(CASE WHEN D.CAPITOL NOT IN  (100)  THEN NVAL(D.COL4)+ NVAL(D.COL5) + NVAL(D.COL6) + NVAL(D.COL7) + NVAL(D.COL8)  ELSE 0 END) >  0
