SELECT 
'Timpul utilizat pentru completarea formularului (<= 360 minute ) - '||SUM(CASE WHEN D.CAPITOL = 1202 AND RIND IN ('999') THEN NVAL(D.COL1) ELSE 0 END )
  AS REZULTAT
FROM VW_DATA_ALL D
WHERE
    D.PERIOADA = :PERIOADA
    AND D.CUIIO = :CUIIO
    AND (D.CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS = -1)
    AND D.FORM = :FORM
    AND D.FORM_VERS = :FORM_VERS 
    
    AND (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
   (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
   (:ID_MD=:ID_MD               OR  :ID_MD <> :ID_MD) AND
    D.FORM = 73
    
    
     
    
    
    HAVING 
    
    SUM(CASE WHEN D.CAPITOL = 100 AND RIND IN ('1') THEN NVAL(D.COL1) ELSE 0 END) = 1 
    AND 
    (
    SUM(CASE WHEN D.CAPITOL = 1202 AND RIND IN ('999') THEN NVAL(D.COL1) ELSE 0 END ) = 0 
    OR 
    SUM(CASE WHEN D.CAPITOL = 1202 AND RIND IN ('999') THEN NVAL(D.COL1) ELSE 0 END ) > 360 
    )